image: docker:19.03.5
services:
  - docker:19.03.5-dind

stages:
  - Build
  - Push
  - Deploy

before_script:
  - apk add python3
  - pip3 install awscli==1.18.8
  - docker load --input data/image.tar
  - $(aws ecr get-login --no-include-email --region us-east-1)

Build Staging:
  stage: Build
  before_script: []
  script:
    - echo Building...
    - mkdir data/
    - docker build --compress -t weather-app --build-arg="CONFIG=staging" .
    - docker save --output data/image.tar weather-app
  artifacts:
    name: image
    paths:
      - data/
  rules:
    - if: "$CI_COMMIT_BRANCH == 'main'"

Build Production:
  stage: Build
  before_script: []
  script:
    - echo Building...
    - mkdir data/
    - docker build --compress -t weather-app --build-arg="CONFIG=production" .
    - docker save --output data/image.tar weather-app
  artifacts:
    name: image
    paths:
      - data/
  rules:
    - if: "$CI_COMMIT_BRANCH == 'production'"

Push Staging:
  stage: Push
  script:
    - echo Pushing to Staging Environment...
    - docker tag weather-app $ECR_REPO:staging
    - docker push $ECR_REPO:staging
  rules:
    - if: "$CI_COMMIT_BRANCH == 'main'"

Push Production:
  stage: Push
  script:
    - echo Pushing to Production Environment...
    - docker tag weather-app $ECR_REPO:production
    - docker push $ECR_REPO:production
  rules:
    - if: "$CI_COMMIT_BRANCH == 'production'"

Deploy Staging:
  stage: Deploy
  script:
    - echo Queueing new ECS service...
    - aws ecs update-service --cluster wwa-staging-cluster --service wwa-staging-server --force-new-deployment --region us-east-1
  rules:
    - if: "$CI_COMMIT_BRANCH == 'main'"

Deploy Production:
  stage: Deploy
  script:
    - echo Queueing new ECS service...
    - aws ecs update-service --cluster wwa-production-cluster --service wwa-production-server --force-new-deployment --region us-east-1
  rules:
    - if: "$CI_COMMIT_BRANCH == 'production'"
      when: manual




